# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.9"
    - name: Install poetry
        # https://github.com/abatilo/actions-poetry
      uses: abatilo/actions-poetry@v3.0.0
      with:
        poetry-version: 1.8.3
    - name: Install dependencies
      run: poetry install --no-root
    - name: Lint with isort
      run: |
        poetry run isort .
      continue-on-error: true
    - name: Lint with black
      run: |
        poetry run black --check .
      continue-on-error: true
    - name: Lint with pycln
      run: |
        poetry run pycln --all .
      continue-on-error: true
    - name: Lint with mypy
      run: |
        poetry run mypy .
      continue-on-error: true
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Docker build
      run: |
        docker build -t ksg9482/fastapi-post .
    - name: Login docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Publish to docker hub
      run: docker push ksg9482/fastapi-post
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          sudo docker-compose -f ~/fastapi-post/docker-compose.hub.yml down 
          sudo docker pull ksg9482/fastapi-post:latest
          sudo docker rmi $(docker images -f "dangling=true" -q)
          sudo docker-compose -f ~/fastapi-post/docker-compose.hub.yml up -d